In [1]:
import pandas as pd
import numpy as np
import ast

In [2]:
movies=pd.read_csv("movies_metadata.csv")
credit=pd.read_csv("credits.csv")

C:\Users\91988\AppData\Local\Temp\ipykernel_12904\2881737850.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  movies=pd.read_csv("movies_metadata.csv")

In [3]:
movies.head()
movies["id"]

0           862
1          8844
2         15602
3         31357
4         11862
          ...
45461    439050
45462    111109
45463     67758
45464    227506
45465    461257
Name: id, Length: 45466, dtype: object

In [4]:
credit.head(50)

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862
5,"[{'cast_id': 25, 'character': 'Lt. Vincent Han...","[{'credit_id': '52fe4292c3a36847f802916d', 'de...",949
6,"[{'cast_id': 1, 'character': 'Linus Larrabee',...","[{'credit_id': '52fe44959251416c75039da9', 'de...",11860
7,"[{'cast_id': 2, 'character': 'Tom Sawyer', 'cr...","[{'credit_id': '52fe46bdc3a36847f810f797', 'de...",45325
8,"[{'cast_id': 1, 'character': 'Darren Francis T...","[{'credit_id': '52fe44dbc3a36847f80ae0f1', 'de...",9091
9,"[{'cast_id': 1, 'character': 'James Bond', 'cr...","[{'credit_id': '52fe426ec3a36847f801e14b', 'de...",710
10,"[{'cast_id': 1, 'character': 'Andrew Shepherd'...","[{'credit_id': '52fe44dac3a36847f80adfa3', 'de...",9087
11,"[{'cast_id': 9, 'character': 'Count Dracula', ...","[{'credit_id': '52fe44b79251416c7503e7fb', 'de...",12110
12,"[{'cast_id': 1, 'character': 'Balto (voice)', ...","[{'credit_id': '593f24b9c3a3680369002371', 'de...",21032
13,"[{'cast_id': 1, 'character': 'Richard Nixon', ...","[{'credit_id': '52fe43c59251416c7501d6f3', 'de...",10858
14,"[{'cast_id': 1, 'character': 'Morgan Adams', '...","[{'credit_id': '52fe42f4c3a36847f802f69f', 'de...",1408
15,"[{'cast_id': 4, 'character': ""Sam 'Ace' Rothst...","[{'credit_id': '52fe424dc3a36847f80139cd', 'de...",524
16,"[{'cast_id': 6, 'character': 'Marianne Dashwoo...","[{'credit_id': '52fe43cec3a36847f807101f', 'de...",4584
17,"[{'cast_id': 42, 'character': 'Ted the Bellhop...","[{'credit_id': '52fe420dc3a36847f800011b', 'de...",5
18,"[{'cast_id': 1, 'character': 'Ace Ventura', 'c...","[{'credit_id': '52fe44dfc3a36847f80af28b', 'de...",9273
19,"[{'cast_id': 1, 'character': 'John', 'credit_i...","[{'credit_id': '52fe44509251416c750305a1', 'de...",11517
20,"[{'cast_id': 1, 'character': 'Chili Palmer', '...","[{'credit_id': '52fe448dc3a36847f809c729', 'de...",8012
21,"[{'cast_id': 8, 'character': 'Helen Hudson', '...","[{'credit_id': '52fe430ec3a36847f803722d', 'de...",1710
22,"[{'cast_id': 1, 'character': 'Robert Rath', 'c...","[{'credit_id': '52fe451cc3a36847f80bd145', 'de...",9691
23,"[{'cast_id': 1, 'character': 'Jessie Caldwell'...","[{'credit_id': '52fe45129251416c7504ab67', 'de...",12665
24,"[{'cast_id': 1, 'character': 'Ben Sanderson', ...","[{'credit_id': '52fe4245c3a36847f80111c3', 'de...",451
25,"[{'cast_id': 2, 'character': 'Othello', 'credi...","[{'credit_id': '5462510ec3a368082d000121', 'de...",16420
26,"[{'cast_id': 9, 'character': 'Young Roberta Ma...","[{'credit_id': '52fe44dec3a36847f80aed45', 'de...",9263
27,"[{'cast_id': 1, 'character': 'Anne Elliott', '...","[{'credit_id': '52fe46ff9251416c7508a8b3', 'de...",17015
28,"[{'cast_id': 24, 'character': 'One', 'credit_i...","[{'credit_id': '52fe428ac3a36847f8026c6f', 'de...",902
29,"[{'cast_id': 2, 'character': 'Xiao Jingbao', '...","[{'credit_id': '52fe46559251416c910511c9', 'de...",37557
30,"[{'cast_id': 13, 'character': 'Louanne Johnson...","[{'credit_id': '52fe4546c3a36847f80c4e4b', 'de...",9909
31,"[{'cast_id': 41, 'character': 'James Cole', 'c...","[{'credit_id': '52fe4212c3a36847f8001ac7', 'de...",63
32,"[{'cast_id': 2, 'character': 'Henri Guillaumet...","[{'credit_id': '52fe49b4c3a368484e13a259', 'de...",78802
33,"[{'cast_id': 1, 'character': 'Babe the Gallant...","[{'credit_id': '52fe450fc3a36847f80b9ff7', 'de...",9598
34,"[{'cast_id': 1, 'character': 'Dora Carrington'...","[{'credit_id': '58594c1ac3a3682fb807e4cf', 'de...",47018
35,"[{'cast_id': 7, 'character': 'Sister Helen Pre...","[{'credit_id': '52fe426ac3a36847f801cf35', 'de...",687
36,"[{'cast_id': 12, 'character': 'Tomas Minton', ...","[{'credit_id': '5554ba2c9251416ddf002acb', 'de...",139405
37,"[{'cast_id': 1, 'character': 'Diane Barrows', ...","[{'credit_id': '52fe45309251416c9102a49d', 'de...",33689
38,"[{'cast_id': 8, 'character': 'Cher Horowitz', ...","[{'credit_id': '52fe4510c3a36847f80ba261', 'de...",9603
39,"[{'cast_id': 4, 'character': 'Rev. Stephen Kum...","[{'credit_id': '52fe456f9251416c91032375', 'de...",34615
40,"[{'cast_id': 1, 'character': 'Richard III', 'c...","[{'credit_id': '52fe44669251416c9100f5a3', 'de...",31174
41,"[{'cast_id': 1, 'character': 'Anthony Curtis',...","[{'credit_id': '52fe44409251416c7502e1d5', 'de...",11443
42,"[{'cast_id': 1, 'character': 'Robert Merivel',...","[{'credit_id': '52fe45999251416c91037fdf', 'de...",35196
43,"[{'cast_id': 1, 'character': 'Lord Rayden', 'c...","[{'credit_id': '52fe44e6c3a36847f80b0899', 'de...",9312
44,"[{'cast_id': 4, 'character': 'Suzanne Stone Ma...","[{'credit_id': '52fe4255c3a36847f8015f49', 'de...",577
45,"[{'cast_id': 1, 'character': 'Finn Dodd', 'cre...","[{'credit_id': '52fe44959251416c75039e1d', 'de...",11861
46,"[{'cast_id': 17, 'character': 'Detective David...","[{'credit_id': '52fe4279c3a36847f802176f', 'de...",807
47,"[{'cast_id': 1, 'character': 'Pocahontas (voic...","[{'credit_id': '52fe43819251416c75013087', 'de...",10530
48,"[{'cast_id': 1, 'character': 'Camille Baker', ...","[{'credit_id': '52fe44a4c3a36847f80a1e53', 'de...",8391
49,"[{'cast_id': 19, 'character': 'Michael McManus...","[{'credit_id': '52fe4260c3a36847f8019a7d', 'de...",629

In [5]:
movies_df=pd.concat([movies,credit],axis=1)
movies_df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,spoken_languages,status,tagline,title,video,vote_average,vote_count,cast,crew,id
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

In [6]:
movies_df=movies_df[["id","title","overview","genres","cast","crew"]]
movies_df.head()

,id,id,title,overview,genres,cast,crew
0,862,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de..."
1,8844,8844,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...","[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de..."
2,15602,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...","[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de..."
3,31357,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de..."
4,11862,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]","[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de..."

In [7]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45476 entries, 0 to 45475
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        45466 non-null  object
 1   id        45476 non-null  int64
 2   title     45460 non-null  object
 3   overview  44512 non-null  object
 4   genres    45466 non-null  object
 5   cast      45476 non-null  object
 6   crew      45476 non-null  object
dtypes: int64(1), object(6)
memory usage: 2.8+ MB

In [8]:
movies_df.isnull().sum()

id           10
id            0
title        16
overview    964
genres       10
cast          0
crew          0
dtype: int64

In [9]:
movies_df.dropna(inplace=True)

In [10]:
movies_df.isnull().sum()

id          0
id          0
title       0
overview    0
genres      0
cast        0
crew        0
dtype: int64

In [11]:
movies_df.duplicated().sum()

8

In [12]:
movies_df.drop_duplicates()

,id,id,title,overview,genres,cast,crew
0,862,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de..."
1,8844,8844,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...","[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de..."
2,15602,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...","[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de..."
3,31357,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de..."
4,11862,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]","[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de..."
...,...,...,...,...,...,...,...
45461,439050,106807,Subdue,Rising and falling between a man and woman.,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...","[{'cast_id': 2, 'character': '', 'credit_id': ...","[{'credit_id': '52fe4a71c3a36847f81ce35b', 'de..."
45462,111109,276895,Century of Birthing,An artist struggles to finish his work while a...,"[{'id': 18, 'name': 'Drama'}]",[],"[{'credit_id': '539ef1090e0a263dd00000d7', 'de..."
45463,67758,404604,Betrayal,"When one of her hits goes wrong, a professiona...","[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...","[{'cast_id': 1, 'character': 'Devki Sabarwal',...","[{'credit_id': '58ee55bbc3a3683df500bd0f', 'de..."
45464,227506,420346,Satan Triumphant,"In a small town live two brothers, one a minis...",[],"[{'cast_id': 0, 'character': 'Lauren', 'credit...","[{'credit_id': '587626f4c3a3682b33008299', 'de..."
45465,461257,67179,Queerama,50 years after decriminalisation of homosexual...,[],"[{'cast_id': 5, 'character': '', 'credit_id': ...","[{'credit_id': '5330178a9251413a720055e3', 'de..."

In [13]:
movies_df.duplicated().sum()

8

In [14]:
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i["name"])
    return L

In [15]:
movies_df["genres"]=movies_df["genres"].apply(convert)
movies_df.head()

,id,id,title,overview,genres,cast,crew
0,862,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[Animation, Comedy, Family]","[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de..."
1,8844,8844,Jumanji,When siblings Judy and Peter discover an encha...,"[Adventure, Fantasy, Family]","[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de..."
2,15602,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[Romance, Comedy]","[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de..."
3,31357,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[Comedy, Drama, Romance]","[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de..."
4,11862,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,[Comedy],"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de..."

In [16]:
def convert_cast(obj):
    L=[]
    count=0
    for i in ast.literal_eval(obj):
        if count<3:
            L.append(i["name"])
            count+=1
        else:
            break
    return L

In [17]:
movies_df["cast"]=movies_df["cast"].apply(convert_cast)

In [18]:
movies_df.head()

,id,id,title,overview,genres,cast,crew
0,862,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[Animation, Comedy, Family]","[Tom Hanks, Tim Allen, Don Rickles]","[{'credit_id': '52fe4284c3a36847f8024f49', 'de..."
1,8844,8844,Jumanji,When siblings Judy and Peter discover an encha...,"[Adventure, Fantasy, Family]","[Robin Williams, Jonathan Hyde, Kirsten Dunst]","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de..."
2,15602,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[Romance, Comedy]","[Walter Matthau, Jack Lemmon, Ann-Margret]","[{'credit_id': '52fe466a9251416c75077a89', 'de..."
3,31357,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[Comedy, Drama, Romance]","[Whitney Houston, Angela Bassett, Loretta Devine]","[{'credit_id': '52fe44779251416c91011acb', 'de..."
4,11862,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,[Comedy],"[Steve Martin, Diane Keaton, Martin Short]","[{'credit_id': '52fe44959251416c75039ed7', 'de..."

In [19]:
movies_df["crew"].values[0]

'[{\'credit_id\': \'52fe4284c3a36847f8024f49\', \'department\': \'Directing\', \'gender\': 2, \'id\': 7879, \'job\': \'Director\', \'name\': \'John Lasseter\', \'profile_path\': \'/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f4f\', \'department\': \'Writing\', \'gender\': 2, \'id\': 12891, \'job\': \'Screenplay\', \'name\': \'Joss Whedon\', \'profile_path\': \'/dTiVsuaTVTeGmvkhcyJvKp2A5kr.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f55\', \'department\': \'Writing\', \'gender\': 2, \'id\': 7, \'job\': \'Screenplay\', \'name\': \'Andrew Stanton\', \'profile_path\': \'/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f5b\', \'department\': \'Writing\', \'gender\': 2, \'id\': 12892, \'job\': \'Screenplay\', \'name\': \'Joel Cohen\', \'profile_path\': \'/dAubAiZcvKFbboWlj7oXOkZnTSu.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f61\', \'department\': \'Writing\', \'gender\': 0, \'id\': 12893, \'job\': \'Screenplay\', \'name\': \'Alec Sokolow\', \'profile_path\': \'/v79vlRYi94BZUQnkkyznbGUZLjT.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f67\', \'department\': \'Production\', \'gender\': 1, \'id\': 12894, \'job\': \'Producer\', \'name\': \'Bonnie Arnold\', \'profile_path\': None}, {\'credit_id\': \'52fe4284c3a36847f8024f6d\', \'department\': \'Production\', \'gender\': 0, \'id\': 12895, \'job\': \'Executive Producer\', \'name\': \'Ed Catmull\', \'profile_path\': None}, {\'credit_id\': \'52fe4284c3a36847f8024f73\', \'department\': \'Production\', \'gender\': 2, \'id\': 12896, \'job\': \'Producer\', \'name\': \'Ralph Guggenheim\', \'profile_path\': None}, {\'credit_id\': \'52fe4284c3a36847f8024f79\', \'department\': \'Production\', \'gender\': 2, \'id\': 12897, \'job\': \'Executive Producer\', \'name\': \'Steve Jobs\', \'profile_path\': \'/mOMP3SwD5qWQSR0ldCIByd3guTV.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f8b\', \'department\': \'Editing\', \'gender\': 2, \'id\': 8, \'job\': \'Editor\', \'name\': \'Lee Unkrich\', \'profile_path\': \'/bdTCCXjgOV3YyaNmLGYGOxFQMOc.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f91\', \'department\': \'Art\', \'gender\': 2, \'id\': 7883, \'job\': \'Art Direction\', \'name\': \'Ralph Eggleston\', \'profile_path\': \'/uUfcGKDsKO1aROMpXRs67Hn6RvR.jpg\'}, {\'credit_id\': \'598331bf925141421201044b\', \'department\': \'Editing\', \'gender\': 2, \'id\': 1168870, \'job\': \'Editor\', \'name\': \'Robert Gordon\', \'profile_path\': None}, {\'credit_id\': \'5892168cc3a36809660095f9\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1552883, \'job\': \'Foley Editor\', \'name\': \'Mary Helen Leasman\', \'profile_path\': None}, {\'credit_id\': \'5531824d9251415289000945\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1453514, \'job\': \'Animation\', \'name\': \'Kim Blanchette\', \'profile_path\': None}, {\'credit_id\': \'589215969251412dcb009bf6\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1414182, \'job\': \'ADR Editor\', \'name\': \'Marilyn McCoppen\', \'profile_path\': None}, {\'credit_id\': \'589217099251412dc500a018\', \'department\': \'Sound\', \'gender\': 2, \'id\': 7885, \'job\': \'Orchestrator\', \'name\': \'Randy Newman\', \'profile_path\': \'/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg\'}, {\'credit_id\': \'5693e6b29251417b0e0000e3\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1429549, \'job\': \'Color Timer\', \'name\': \'Dale E. Grahn\', \'profile_path\': None}, {\'credit_id\': \'572e2522c3a36869e6001a9c\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 7949, \'job\': \'CG Painter\', \'name\': \'Robin Cooper\', \'profile_path\': None}, {\'credit_id\': \'574f12309251415ca1000012\', \'department\': \'Writing\', \'gender\': 2, \'id\': 7879, \'job\': \'Original Story\', \'name\': \'John Lasseter\', \'profile_path\': \'/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg\'}, {\'credit_id\': \'574f1240c3a3682e7300001c\', \'department\': \'Writing\', \'gender\': 2, \'id\': 12890, \'job\': \'Original Story\', \'name\': \'Pete Docter\', \'profile_path\': \'/r6ngPgnReA3RHmKjmSoVsc6Awjp.jpg\'}, {\'credit_id\': \'574f12519251415c92000015\', \'department\': \'Writing\', \'gender\': 0, \'id\': 7911, \'job\': \'Original Story\', \'name\': \'Joe Ranft\', \'profile_path\': \'/f1BoWC2JbCcfP1e5hKfGsxkHzVU.jpg\'}, {\'credit_id\': \'574f12cec3a3682e82000022\', \'department\': \'Crew\', \'gender\': 0, \'id\': 1629419, \'job\': \'Post Production Supervisor\', \'name\': \'Patsy Bouge\', \'profile_path\': None}, {\'credit_id\': \'574f14f19251415ca1000082\', \'department\': \'Art\', \'gender\': 0, \'id\': 7961, \'job\': \'Sculptor\', \'name\': \'Norm DeCarlo\', \'profile_path\': None}, {\'credit_id\': \'5751ae4bc3a3683772002b7f\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 12905, \'job\': \'Animation Director\', \'name\': \'Ash Brannon\', \'profile_path\': \'/6ueWgPEEBHvS3De2BHYQnYjRTig.jpg\'}, {\'credit_id\': \'5891edbe9251412dc5007cd6\', \'department\': \'Sound\', \'gender\': 2, \'id\': 7885, \'job\': \'Music\', \'name\': \'Randy Newman\', \'profile_path\': \'/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg\'}, {\'credit_id\': \'589213d39251412dc8009832\', \'department\': \'Directing\', \'gender\': 0, \'id\': 1748707, \'job\': \'Layout\', \'name\': \'Roman Figun\', \'profile_path\': None}, {\'credit_id\': \'5892173dc3a3680968009351\', \'department\': \'Sound\', \'gender\': 2, \'id\': 4949, \'job\': \'Orchestrator\', \'name\': \'Don Davis\', \'profile_path\': None}, {\'credit_id\': \'589217cec3a3686b0a0052ba\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1372885, \'job\': \'Music Editor\', \'name\': \'James Flamberg\', \'profile_path\': None}, {\'credit_id\': \'58921831c3a3686348004a64\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1739962, \'job\': \'Negative Cutter\', \'name\': \'Mary Beth Smith\', \'profile_path\': None}, {\'credit_id\': \'58921838c3a36809700096c0\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748513, \'job\': \'Negative Cutter\', \'name\': \'Rick Mackay\', \'profile_path\': None}, {\'credit_id\': \'589218429251412dd1009d1b\', \'department\': \'Art\', \'gender\': 0, \'id\': 1458006, \'job\': \'Title Designer\', \'name\': \'Susan Bradley\', \'profile_path\': None}, {\'credit_id\': \'5891ed99c3a3680966007670\', \'department\': \'Crew\', \'gender\': 0, \'id\': 1748557, \'job\': \'Supervising Technical Director\', \'name\': \'William Reeves\', \'profile_path\': None}, {\'credit_id\': \'5891edcec3a3686b0a002eb2\', \'department\': \'Sound\', \'gender\': 2, \'id\': 7885, \'job\': \'Songs\', \'name\': \'Randy Newman\', \'profile_path\': \'/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg\'}, {\'credit_id\': \'5891edf9c3a36809700075e6\', \'department\': \'Writing\', \'gender\': 2, \'id\': 7, \'job\': \'Original Story\', \'name\': \'Andrew Stanton\', \'profile_path\': \'/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg\'}, {\'credit_id\': \'58920f0b9251412dd7009104\', \'department\': \'Crew\', \'gender\': 2, \'id\': 12890, \'job\': \'Supervising Animator\', \'name\': \'Pete Docter\', \'profile_path\': \'/r6ngPgnReA3RHmKjmSoVsc6Awjp.jpg\'}, {\'credit_id\': \'58920f1fc3a3680977009021\', \'department\': \'Sound\', \'gender\': 2, \'id\': 2216, \'job\': \'Sound Designer\', \'name\': \'Gary Rydstrom\', \'profile_path\': \'/jZpr1nVfO7lldWI0YtmP1FGw7Rj.jpg\'}, {\'credit_id\': \'58920f389251412dd700912d\', \'department\': \'Production\', \'gender\': 0, \'id\': 12909, \'job\': \'Production Supervisor\', \'name\': \'Karen Robert Jackson\', \'profile_path\': None}, {\'credit_id\': \'58920fbd9251412dcb00969c\', \'department\': \'Crew\', \'gender\': 0, \'id\': 953331, \'job\': \'Executive Music Producer\', \'name\': \'Chris Montan\', \'profile_path\': None}, {\'credit_id\': \'589210069251412dd7009219\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 7893, \'job\': \'Animation Director\', \'name\': \'Rich Quade\', \'profile_path\': None}, {\'credit_id\': \'589210329251412dcd00943b\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8025, \'job\': \'Animation\', \'name\': \'Michael Berenstein\', \'profile_path\': None}, {\'credit_id\': \'5892103bc3a368096a009180\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 78009, \'job\': \'Animation\', \'name\': \'Colin Brady\', \'profile_path\': None}, {\'credit_id\': \'5892105dc3a3680968008db2\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748682, \'job\': \'Animation\', \'name\': \'Davey Crockett Feiten\', \'profile_path\': None}, {\'credit_id\': \'589210669251412dcd009466\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1454030, \'job\': \'Animation\', \'name\': \'Angie Glocka\', \'profile_path\': None}, {\'credit_id\': \'5892107c9251412dd1009613\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748683, \'job\': \'Animation\', \'name\': \'Rex Grignon\', \'profile_path\': None}, {\'credit_id\': \'5892108ac3a3680973008d3f\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748684, \'job\': \'Animation\', \'name\': \'Tom K. Gurney\', \'profile_path\': None}, {\'credit_id\': \'58921093c3a3686348004477\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 8029, \'job\': \'Animation\', \'name\': \'Jimmy Hayward\', \'profile_path\': \'/lTDRpudEY7BDwTefXbXzMlmb0ui.jpg\'}, {\'credit_id\': \'5892109b9251412dcd0094b0\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1426773, \'job\': \'Animation\', \'name\': \'Hal T. Hickel\', \'profile_path\': None}, {\'credit_id\': \'589210a29251412dc5009a29\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8035, \'job\': \'Animation\', \'name\': \'Karen Kiser\', \'profile_path\': None}, {\'credit_id\': \'589210ccc3a3680977009191\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748688, \'job\': \'Animation\', \'name\': \'Anthony B. LaMolinara\', \'profile_path\': None}, {\'credit_id\': \'589210d7c3a3686b0a004c1f\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 587314, \'job\': \'Animation\', \'name\': \'Guionne Leroy\', \'profile_path\': None}, {\'credit_id\': \'589210e1c3a36809770091a7\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7918, \'job\': \'Animation\', \'name\': \'Bud Luckey\', \'profile_path\': \'/pcCh7G19FKMNijmPQg1PMH1btic.jpg\'}, {\'credit_id\': \'589210ee9251412dc200978a\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748689, \'job\': \'Animation\', \'name\': \'Les Major\', \'profile_path\': None}, {\'credit_id\': \'589210fa9251412dc8009595\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7892, \'job\': \'Animation\', \'name\': \'Glenn McQueen\', \'profile_path\': None}, {\'credit_id\': \'589211029251412dc8009598\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 555795, \'job\': \'Animation\', \'name\': \'Mark Oftedal\', \'profile_path\': None}, {\'credit_id\': \'5892110b9251412dc800959d\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7882, \'job\': \'Animation\', \'name\': \'Jeff Pidgeon\', \'profile_path\': \'/yLddkg5HcgbJg00cS13GVBnP0HY.jpg\'}, {\'credit_id\': \'58921113c3a36863480044e4\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8017, \'job\': \'Animation\', \'name\': \'Jeff Pratt\', \'profile_path\': None}, {\'credit_id\': \'5892111c9251412dcb0097e9\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1184140, \'job\': \'Animation\', \'name\': \'Steve Rabatich\', \'profile_path\': None}, {\'credit_id\': \'58921123c3a36809700090f6\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8049, \'job\': \'Animation\', \'name\': \'Roger Rose\', \'profile_path\': None}, {\'credit_id\': \'5892112b9251412dcb0097fb\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1509559, \'job\': \'Animation\', \'name\': \'Steve Segal\', \'profile_path\': None}, {\'credit_id\': \'589211349251412dc80095c3\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748691, \'job\': \'Animation\', \'name\': \'Doug Sheppeck\', \'profile_path\': None}, {\'credit_id\': \'5892113cc3a3680970009106\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8050, \'job\': \'Animation\', \'name\': \'Alan Sperling\', \'profile_path\': None}, {\'credit_id\': \'58921148c3a3686b0a004c99\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8010, \'job\': \'Animation\', \'name\': \'Doug Sweetland\', \'profile_path\': None}, {\'credit_id\': \'58921150c3a3680966009125\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8044, \'job\': \'Animation\', \'name\': \'David Tart\', \'profile_path\': None}, {\'credit_id\': \'589211629251412dc5009b00\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1454034, \'job\': \'Animation\', \'name\': \'Ken Willard\', \'profile_path\': None}, {\'credit_id\': \'589211c1c3a3686b0a004d28\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 7887, \'job\': \'Visual Effects Supervisor\', \'name\': \'Thomas Porter\', \'profile_path\': None}, {\'credit_id\': \'589211d4c3a3680968008ed9\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1406878, \'job\': \'Visual Effects\', \'name\': \'Mark Thomas Henne\', \'profile_path\': None}, {\'credit_id\': \'589211f59251412dd4008e65\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748698, \'job\': \'Visual Effects\', \'name\': \'Oren Jacob\', \'profile_path\': None}, {\'credit_id\': \'58921242c3a368096a00939b\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748699, \'job\': \'Visual Effects\', \'name\': \'Darwyn Peachey\', \'profile_path\': None}, {\'credit_id\': \'5892124b9251412dc5009bd2\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748701, \'job\': \'Visual Effects\', \'name\': \'Mitch Prater\', \'profile_path\': None}, {\'credit_id\': \'58921264c3a3686b0a004dbf\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748703, \'job\': \'Visual Effects\', \'name\': \'Brian M. Rosen\', \'profile_path\': None}, {\'credit_id\': \'589212709251412dcd009676\', \'department\': \'Lighting\', \'gender\': 1, \'id\': 12912, \'job\': \'Lighting Supervisor\', \'name\': \'Sharon Calahan\', \'profile_path\': None}, {\'credit_id\': \'5892127fc3a3686b0a004de5\', \'department\': \'Lighting\', \'gender\': 0, \'id\': 7899, \'job\': \'Lighting Supervisor\', \'name\': \'Galyn Susman\', \'profile_path\': None}, {\'credit_id\': \'589212cdc3a3680970009268\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 12915, \'job\': \'CG Painter\', \'name\': \'William Cone\', \'profile_path\': None}, {\'credit_id\': \'5892130f9251412dc8009791\', \'department\': \'Art\', \'gender\': 0, \'id\': 1748705, \'job\': \'Sculptor\', \'name\': \'Shelley Daniels Lekven\', \'profile_path\': None}, {\'credit_id\': \'5892131c9251412dd4008f4c\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7889, \'job\': \'Character Designer\', \'name\': \'Bob Pauley\', \'profile_path\': None}, {\'credit_id\': \'589213249251412dd100987b\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7918, \'job\': \'Character Designer\', \'name\': \'Bud Luckey\', \'profile_path\': \'/pcCh7G19FKMNijmPQg1PMH1btic.jpg\'}, {\'credit_id\': \'5892132b9251412dc80097b1\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7, \'job\': \'Character Designer\', \'name\': \'Andrew Stanton\', \'profile_path\': \'/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg\'}, {\'credit_id\': \'58921332c3a368634800467b\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 12915, \'job\': \'Character Designer\', \'name\': \'William Cone\', \'profile_path\': None}, {\'credit_id\': \'5892135f9251412dd4008f90\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748706, \'job\': \'Character Designer\', \'name\': \'Steve Johnson\', \'profile_path\': None}, {\'credit_id\': \'58921384c3a3680973008fd4\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1176752, \'job\': \'Character Designer\', \'name\': \'Dan Haskett\', \'profile_path\': None}, {\'credit_id\': \'5892138e9251412dc20099fc\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1088034, \'job\': \'Character Designer\', \'name\': \'Tom Holloway\', \'profile_path\': \'/a0r0T2usTBpgMI5aZbRBDW1fTl8.jpg\'}, {\'credit_id\': \'58921395c3a368097700942f\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1447465, \'job\': \'Character Designer\', \'name\': \'Jean Gillmore\', \'profile_path\': None}, {\'credit_id\': \'589213e2c3a3680973009026\', \'department\': \'Directing\', \'gender\': 0, \'id\': 1748709, \'job\': \'Layout\', \'name\': \'Desirée Mourad\', \'profile_path\': None}, {\'credit_id\': \'589214099251412dc5009d57\', \'department\': \'Art\', \'gender\': 0, \'id\': 1748710, \'job\': \'Set Dresser\', \'name\': "Kelly O\'Connell", \'profile_path\': None}, {\'credit_id\': \'58921411c3a3686b0a004f70\', \'department\': \'Art\', \'gender\': 0, \'id\': 1443471, \'job\': \'Set Dresser\', \'name\': \'Sonoko Konishi\', \'profile_path\': None}, {\'credit_id\': \'58921434c3a368096a00956e\', \'department\': \'Art\', \'gender\': 0, \'id\': 1748711, \'job\': \'Set Dresser\', \'name\': \'Ann M. Rockwell\', \'profile_path\': None}, {\'credit_id\': \'5892144ac3a36809680090de\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748712, \'job\': \'Editorial Manager\', \'name\': \'Julie M. McDonald\', \'profile_path\': None}, {\'credit_id\': \'58921479c3a368096800910f\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1589729, \'job\': \'Assistant Editor\', \'name\': \'Robin Lee\', \'profile_path\': None}, {\'credit_id\': \'5892148b9251412dd10099cc\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748716, \'job\': \'Assistant Editor\', \'name\': \'Tom Freeman\', \'profile_path\': None}, {\'credit_id\': \'589214959251412dcb009b1f\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748717, \'job\': \'Assistant Editor\', \'name\': \'Ada Cochavi\', \'profile_path\': None}, {\'credit_id\': \'5892149ec3a3686348004798\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1336438, \'job\': \'Assistant Editor\', \'name\': \'Dana Mulligan\', \'profile_path\': None}, {\'credit_id\': \'589214adc3a368096a0095db\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748718, \'job\': \'Editorial Coordinator\', \'name\': \'Deirdre Morrison\', \'profile_path\': None}, {\'credit_id\': \'589214c7c3a368097700952b\', \'department\': \'Production\', \'gender\': 0, \'id\': 1748719, \'job\': \'Production Coordinator\', \'name\': \'Lori Lombardo\', \'profile_path\': None}, {\'credit_id\': \'589214cec3a368096a009603\', \'department\': \'Production\', \'gender\': 0, \'id\': 1748720, \'job\': \'Production Coordinator\', \'name\': \'Ellen Devine\', \'profile_path\': None}, {\'credit_id\': \'589214e39251412dc8009904\', \'department\': \'Crew\', \'gender\': 0, \'id\': 1468014, \'job\': \'Unit Publicist\', \'name\': \'Lauren Beth Strogoff\', \'profile_path\': None}, {\'credit_id\': \'58921544c3a3686b0a00507d\', \'department\': \'Sound\', \'gender\': 2, \'id\': 2216, \'job\': \'Sound Re-Recording Mixer\', \'name\': \'Gary Rydstrom\', \'profile_path\': \'/jZpr1nVfO7lldWI0YtmP1FGw7Rj.jpg\'}, {\'credit_id\': \'5892154c9251412dd1009a56\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1425978, \'job\': \'Sound Re-Recording Mixer\', \'name\': \'Gary Summers\', \'profile_path\': None}, {\'credit_id\': \'58921555c3a36809680091bd\', \'department\': \'Sound\', \'gender\': 2, \'id\': 8276, \'job\': \'Supervising Sound Editor\', \'name\': \'Tim Holland\', \'profile_path\': None}, {\'credit_id\': \'589215c39251412dcb009c12\', \'department\': \'Sound\', \'gender\': 0, \'id\': 7069, \'job\': \'Sound Effects Editor\', \'name\': \'Pat Jackson\', \'profile_path\': None}, {\'credit_id\': \'58921698c3a368096a009788\', \'department\': \'Crew\', \'gender\': 2, \'id\': 15894, \'job\': \'Sound Design Assistant\', \'name\': \'Tom Myers\', \'profile_path\': None}, {\'credit_id\': \'589216a89251412dc2009ca4\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1414177, \'job\': \'Assistant Sound Editor\', \'name\': \'J.R. 

In [20]:
def convert_crew(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i["job"]=="Director":
            L.append(i["name"])
    return L

In [21]:
movies_df["crew"]=movies_df["crew"].apply(convert_crew)

In [22]:
movies_df["crew"].values[0]

['John Lasseter']

In [23]:
movies_df["overview"]=movies_df["overview"].apply(lambda x:x.split())

In [24]:
movies_df.head()

,id,id,title,overview,genres,cast,crew
0,862,862,Toy Story,"[Led, by, Woody,, Andy's, toys, live, happily,...","[Animation, Comedy, Family]","[Tom Hanks, Tim Allen, Don Rickles]",[John Lasseter]
1,8844,8844,Jumanji,"[When, siblings, Judy, and, Peter, discover, a...","[Adventure, Fantasy, Family]","[Robin Williams, Jonathan Hyde, Kirsten Dunst]",[Joe Johnston]
2,15602,15602,Grumpier Old Men,"[A, family, wedding, reignites, the, ancient, ...","[Romance, Comedy]","[Walter Matthau, Jack Lemmon, Ann-Margret]",[Howard Deutch]
3,31357,31357,Waiting to Exhale,"[Cheated, on,, mistreated, and, stepped, on,, ...","[Comedy, Drama, Romance]","[Whitney Houston, Angela Bassett, Loretta Devine]",[Forest Whitaker]
4,11862,11862,Father of the Bride Part II,"[Just, when, George, Banks, has, recovered, fr...",[Comedy],"[Steve Martin, Diane Keaton, Martin Short]",[Charles Shyer]

In [25]:
movies_df["overview"]=movies_df["overview"].apply(lambda x:[i.replace(" ","")for i in x])
movies_df["genres"]=movies_df["genres"].apply(lambda x:[i.replace(" ","")for i in x])
#movies["keywords"]=movies["keywords"].apply(lambda x:[i.replace(" ","")for i in x])
movies_df["cast"]=movies_df["cast"].apply(lambda x:[i.replace(" ","")for i in x])
movies_df["crew"]=movies_df["crew"].apply(lambda x:[i.replace(" ","")for i in x])
movies_df.head()

,id,id,title,overview,genres,cast,crew
0,862,862,Toy Story,"[Led, by, Woody,, Andy's, toys, live, happily,...","[Animation, Comedy, Family]","[TomHanks, TimAllen, DonRickles]",[JohnLasseter]
1,8844,8844,Jumanji,"[When, siblings, Judy, and, Peter, discover, a...","[Adventure, Fantasy, Family]","[RobinWilliams, JonathanHyde, KirstenDunst]",[JoeJohnston]
2,15602,15602,Grumpier Old Men,"[A, family, wedding, reignites, the, ancient, ...","[Romance, Comedy]","[WalterMatthau, JackLemmon, Ann-Margret]",[HowardDeutch]
3,31357,31357,Waiting to Exhale,"[Cheated, on,, mistreated, and, stepped, on,, ...","[Comedy, Drama, Romance]","[WhitneyHouston, AngelaBassett, LorettaDevine]",[ForestWhitaker]
4,11862,11862,Father of the Bride Part II,"[Just, when, George, Banks, has, recovered, fr...",[Comedy],"[SteveMartin, DianeKeaton, MartinShort]",[CharlesShyer]

In [26]:
movies_df["tags"]=movies_df["overview"]+movies_df["genres"]+movies_df["cast"]+movies_df["crew"]
movies_df.head()

,id,id,title,overview,genres,cast,crew,tags
0,862,862,Toy Story,"[Led, by, Woody,, Andy's, toys, live, happily,...","[Animation, Comedy, Family]","[TomHanks, TimAllen, DonRickles]",[JohnLasseter],"[Led, by, Woody,, Andy's, toys, live, happily,..."
1,8844,8844,Jumanji,"[When, siblings, Judy, and, Peter, discover, a...","[Adventure, Fantasy, Family]","[RobinWilliams, JonathanHyde, KirstenDunst]",[JoeJohnston],"[When, siblings, Judy, and, Peter, discover, a..."
2,15602,15602,Grumpier Old Men,"[A, family, wedding, reignites, the, ancient, ...","[Romance, Comedy]","[WalterMatthau, JackLemmon, Ann-Margret]",[HowardDeutch],"[A, family, wedding, reignites, the, ancient, ..."
3,31357,31357,Waiting to Exhale,"[Cheated, on,, mistreated, and, stepped, on,, ...","[Comedy, Drama, Romance]","[WhitneyHouston, AngelaBassett, LorettaDevine]",[ForestWhitaker],"[Cheated, on,, mistreated, and, stepped, on,, ..."
4,11862,11862,Father of the Bride Part II,"[Just, when, George, Banks, has, recovered, fr...",[Comedy],"[SteveMartin, DianeKeaton, MartinShort]",[CharlesShyer],"[Just, when, George, Banks, has, recovered, fr..."

In [27]:
new_df=movies_df[["id","title","tags"]]

new_df.head()

,id,id,title,tags
0,862,862,Toy Story,"[Led, by, Woody,, Andy's, toys, live, happily,..."
1,8844,8844,Jumanji,"[When, siblings, Judy, and, Peter, discover, a..."
2,15602,15602,Grumpier Old Men,"[A, family, wedding, reignites, the, ancient, ..."
3,31357,31357,Waiting to Exhale,"[Cheated, on,, mistreated, and, stepped, on,, ..."
4,11862,11862,Father of the Bride Part II,"[Just, when, George, Banks, has, recovered, fr..."

In [28]:
new_df["tags"]=new_df["tags"].apply(lambda x:" ".join(x))

C:\Users\91988\AppData\Local\Temp\ipykernel_12904\335573094.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"]=new_df["tags"].apply(lambda x:" ".join(x))

In [29]:
new_df["tags"]=new_df["tags"].str.lower()
new_df.head()

C:\Users\91988\AppData\Local\Temp\ipykernel_12904\1488118980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"]=new_df["tags"].str.lower()

,id,id,title,tags
0,862,862,Toy Story,"led by woody, andy's toys live happily in his ..."
1,8844,8844,Jumanji,when siblings judy and peter discover an encha...
2,15602,15602,Grumpier Old Men,a family wedding reignites the ancient feud be...
3,31357,31357,Waiting to Exhale,"cheated on, mistreated and stepped on, the wom..."
4,11862,11862,Father of the Bride Part II,just when george banks has recovered from his ...

In [30]:
import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [31]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [32]:
new_df["tags"]=new_df["tags"].apply(stem)

C:\Users\91988\AppData\Local\Temp\ipykernel_12904\1027202188.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"]=new_df["tags"].apply(stem)

In [33]:
new_df["tags"].values[0]

"led by woody, andy' toy live happili in hi room until andy' birthday bring buzz lightyear onto the scene. afraid of lose hi place in andy' heart, woodi plot against buzz. but when circumst separ buzz and woodi from their owner, the duo eventu learn to put asid their differences. anim comedi famili tomhank timallen donrickl johnlasset"

In [34]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=1000,stop_words="english")

In [35]:
vectors=cv.fit_transform(new_df["tags"]).toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [36]:
vectors.shape

(44506, 1000)

In [37]:
features=cv.get_feature_names_out()
features

array(['000', '10', '12', '15', '20', '30', 'abandon', 'abl', 'abus',
       'accept', 'accid', 'accident', 'account', 'accus', 'act', 'action',
       'actor', 'actress', 'actual', 'adam', 'adapt', 'addict', 'adopt',
       'adult', 'adventur', 'affair', 'affect', 'africa', 'african', 'ag',
       'age', 'agent', 'ago', 'agre', 'aid', 'air', 'alcohol', 'alex',
       'alien', 'allow', 'alon', 'alreadi', 'alway', 'america',
       'american', 'amp', 'ancient', 'angel', 'ani', 'anim', 'ann',
       'anna', 'anoth', 'answer', 'anyth', 'apart', 'appear', 'approach',
       'area', 'arm', 'armi', 'arrest', 'arriv', 'art', 'artist', 'ask',
       'aspir', 'assassin', 'assign', 'assist', 'attack', 'attempt',
       'attend', 'attract', 'author', 'avoid', 'award', 'away', 'babi',
       'bad', 'band', 'bank', 'bar', 'base', 'battl', 'beach', 'bear',
       'beauti', 'becam', 'becaus', 'becom', 'befor', 'befriend', 'begin',
       'believ', 'belov', 'ben', 'best', 'better', 'big', 'birth',
       'bizarr', 'black', 'blind', 'blood', 'board', 'bodi', 'bomb',
       'bond', 'book', 'border', 'born', 'boss', 'box', 'boy',
       'boyfriend', 'break', 'bring', 'british', 'brother', 'brought',
       'brutal', 'build', 'busi', 'business', 'businessman', 'buy',
       'california', 'camera', 'camp', 'captain', 'captur', 'car', 'care',
       'career', 'carri', 'case', 'cast', 'cat', 'catch', 'caught',
       'caus', 'celebr', 'center', 'centuri', 'century', 'challeng',
       'chanc', 'chang', 'charact', 'charg', 'charl', 'charli', 'charm',
       'chase', 'chief', 'child', 'childhood', 'children', 'china',
       'chines', 'choos', 'christma', 'chronicl', 'church', 'citi',
       'city', 'civil', 'claim', 'class', 'classic', 'clear', 'close',
       'club', 'cold', 'collect', 'colleg', 'come', 'comedi', 'comedy',
       'comic', 'command', 'commit', 'common', 'commun', 'compani',
       'company', 'complet', 'complex', 'complic', 'concert', 'conflict',
       'confront', 'connect', 'consid', 'contact', 'continu', 'control',
       'convict', 'convinc', 'cop', 'corpor', 'corrupt', 'countri',
       'country', 'coupl', 'cours', 'court', 'cover', 'crash', 'creat',
       'creatur', 'crew', 'crime', 'crimin', 'cross', 'cultur', 'cut',
       'dad', 'danc', 'dancer', 'danger', 'dark', 'date', 'daughter',
       'david', 'day', 'dead', 'deadli', 'deal', 'death', 'decid', 'deep',
       'defeat', 'defend', 'deliv', 'demon', 'desert', 'design', 'desir',
       'desper', 'despit', 'destroy', 'detect', 'determin', 'develop',
       'did', 'die', 'differ', 'difficult', 'direct', 'director',
       'disappear', 'discov', 'disturb', 'divorc', 'doctor', 'document',
       'documentari', 'doe', 'doesn', 'dog', 'don', 'door', 'dr', 'drama',
       'dramat', 'draw', 'drawn', 'dream', 'dreams', 'drink', 'drive',
       'driver', 'drug', 'dure', 'earli', 'earth', 'east', 'effect',
       'effort', 'embark', 'emot', 'encount', 'end', 'enemi', 'engag',
       'england', 'english', 'enjoy', 'enlist', 'enter', 'entertain',
       'entir', 'epic', 'escap', 'especi', 'estrang', 'eve', 'event',
       'eventu', 'everi', 'everyon', 'everyth', 'evil', 'ex', 'examin',
       'execut', 'exist', 'expect', 'experi', 'explor', 'expos', 'extrem',
       'eye', 'face', 'fact', 'fail', 'faith', 'fall', 'fame', 'famili',
       'family', 'famou', 'fan', 'fantasi', 'far', 'farm', 'farmer',
       'fashion', 'fast', 'fate', 'father', 'fear', 'featur', 'feel',
       'fellow', 'femal', 'fiction', 'fight', 'figur', 'film', 'filmmak',
       'final', 'flee', 'fli', 'focus', 'follow', 'food', 'footag',
       'footbal', 'forc', 'foreign', 'forest', 'form', 'france', 'frank',
       'free', 'freedom', 'french', 'friend', 'friends', 'friendship',
       'fun', 'futur', 'future', 'gain', 'game', 'gang', 'gangster',
       'gay', 'gener', 'georg', 'german', 'ghost', 'giant', 'gift',
       'girl', 'girlfriend', 'girls', 'given', 'god', 'goe', 'gold',
       'gone', 'good', 'got', 'govern', 'great', 'greatest', 'group',
       'grow', 'guard', 'gun', 'guy', 'ha', 'half', 'hand', 'handsom',
       'happen', 'happi', 'hard', 'harri', 'haunt', 'head', 'hear',
       'heart', 'hell', 'help', 'henri', 'hero', 'hi', 'hidden', 'hide',
       'high', 'hilari', 'hire', 'histori', 'history', 'hit', 'hold',
       'holiday', 'hollywood', 'home', 'hope', 'horror', 'hospit', 'host',
       'hot', 'hotel', 'hour', 'hous', 'house', 'human', 'hunt', 'hunter',
       'husband', 'idea', 'ident', 'ii', 'ill', 'imag', 'immedi',
       'import', 'includ', 'increasingli', 'india', 'indian', 'inform',
       'initi', 'innoc', 'insid', 'inspir', 'instead', 'intent', 'intern',
       'interview', 'investig', 'invit', 'involv', 'island', 'isn',
       'isol', 'italian', 'jack', 'jail', 'jame', 'jane', 'japan',
       'japanes', 'jean', 'jewish', 'jim', 'job', 'joe', 'john', 'join',
       'journalist', 'journey', 'just', 'kid', 'kidnap', 'kill', 'killer',
       'kind', 'king', 'know', 'known', 'la', 'ladi', 'land', 'larg',
       'late', 'later', 'law', 'lawyer', 'le', 'lead', 'leader', 'learn',
       'leav', 'led', 'lee', 'left', 'legend', 'legendari', 'let',
       'letter', 'lie', 'life', 'light', 'like', 'line', 'littl', 'live',
       'lives', 'll', 'lo', 'local', 'locat', 'london', 'lone', 'long',
       'look', 'lord', 'lose', 'lost', 'lot', 'love', 'lover', 'low',
       'luck', 'mad', 'magic', 'main', 'major', 'make', 'male', 'man',
       'manag', 'mani', 'mari', 'mark', 'marri', 'marriag', 'marriage',
       'martial', 'martin', 'master', 'match', 'matter', 'max', 'mean',
       'meet', 'member', 'memori', 'men', 'mental', 'met', 'mexican',
       'mexico', 'michael', 'middl', 'middle', 'mike', 'militari',
       'million', 'mind', 'miss', 'mission', 'mix', 'mob', 'model',
       'modern', 'moment', 'money', 'monster', 'month', 'mother',
       'mountain', 'movi', 'movie', 'mr', 'murder', 'music', 'musician',
       'mysteri', 'nation', 'nativ', 'natur', 'nazi', 'near', 'nearli',
       'need', 'neighbor', 'neighborhood', 'new', 'news', 'nick', 'night',
       'normal', 'north', 'noth', 'notori', 'novel', 'nuclear', 'number',
       'obsess', 'odd', 'offer', 'offic', 'old', 'older', 'onc', 'onli',
       'open', 'oper', 'order', 'organ', 'origin', 'orphan', 'outsid',
       'overcom', 'owner', 'pain', 'pair', 'parent', 'parents', 'pari',
       'paris', 'park', 'parti', 'partner', 'pass', 'passion', 'past',
       'path', 'patient', 'paul', 'pay', 'peac', 'peopl', 'people',
       'perfect', 'perform', 'period', 'person', 'peter', 'photograph',
       'pick', 'piec', 'pilot', 'place', 'plan', 'plane', 'planet',
       'play', 'player', 'plot', 'point', 'polic', 'police', 'polit',
       'poor', 'popular', 'portrait', 'possess', 'possibl', 'post',
       'power', 'pregnant', 'prepar', 'present', 'presid', 'prevent',
       'priest', 'princ', 'princess', 'prison', 'privat', 'problem',
       'process', 'produc', 'product', 'profession', 'professor',
       'program', 'project', 'promis', 'protect', 'prove', 'provid',
       'public', 'pull', 'pursu', 'queen', 'quest', 'question', 'quickli',
       'quiet', 'quit', 'race', 'radio', 'rais', 'rare', 'ray', 'reach',
       'read', 'readi', 'real', 'realiti', 'realiz', 'realli', 'reason',
       'receiv', 'recent', 'record', 'recov', 'recruit', 'red', 'refus',
       'relationship', 'releas', 'remain', 'remot', 'report', 'rescu',
       'research', 'resid', 'resist', 'respect', 'respons', 'rest',
       'result', 'retir', 'return', 'reunit', 'reveal', 'reveng',
       'revenge', 'rich', 'richard', 'ride', 'right', 'ring', 'rise',
       'risk', 'rival', 'road', 'rob', 'robert', 'rock', 'role', 'romanc',
       'romant', 'room', 'rule', 'run', 'rural', 'russian', 'ruthless',
       'sam', 'san', 'save', 'say', 'scene', 'scheme', 'school',
       'sciencefict', 'scientist', 'screen', 'sea', 'search', 'second',
       'secret', 'secur', 'seek', 'seemingli', 'seen', 'self', 'sell',
       'send', 'sens', 'sent', 'separ', 'seri', 'serial', 'serv',
       'servic', 'set', 'settl', 'seven', 'sever', 'sex', 'sexual',
       'share', 'sheriff', 'ship', 'shock', 'shoot', 'shop', 'short',
       'shot', 'sign', 'simpl', 'sinc', 'sing', 'singer', 'singl',
       'sister', 'situat', 'skill', 'sleep', 'slowli', 'small', 'smith',
       'social', 'societi', 'society', 'soldier', 'solv', 'someon',
       'someth', 'son', 'song', 'soon', 'soul', 'south', 'soviet',
       'space', 'speak', 'special', 'spend', 'spi', 'spirit', 'sport',
       'stage', 'stand', 'star', 'start', 'state', 'station', 'stay',
       'steal', 'step', 'stolen', 'stop', 'store', 'stori', 'story',
       'strang', 'stranger', 'street', 'strike', 'strong', 'struggl',
       'student', 'studi', 'style', 'subject', 'success', 'suddenli',
       'suffer', 'suicid', 'summer', 'support', 'surpris', 'surround',
       'surviv', 'survivor', 'suspect', 'taken', 'tale', 'talent', 'talk',
       'target', 'task', 'teach', 'teacher', 'team', 'teen', 'teenag',
       'televis', 'tell', 'term', 'terrifi', 'terror', 'terrorist',
       'test', 'themselv', 'thi', 'thief', 'thing', 'think', 'thought',
       'threaten', 'thriller', 'throw', 'tim', 'time', 'today', 'togeth',
       'told', 'tom', 'toni', 'took', 'torn', 'tough', 'tour', 'town',
       'track', 'tradit', 'tragic', 'trail', 'train', 'transform', 'trap',
       'travel', 'tri', 'trial', 'trip', 'troubl', 'true', 'truth',
       'turn', 'tv', 'tvmovi', 'twin', 'twist', 'ultim', 'unabl', 'uncl',
       'uncov', 'underground', 'understand', 'unexpect', 'uniqu', 'unit',
       'univers', 'unknown', 'unlik', 'use', 'vacat', 'vampir', 'van',
       'variou', 'veri', 'version', 'veteran', 'victim', 'video', 'view',
       'villag', 'village', 'violent', 'visit', 'wa', 'wait', 'wake',
       'walk', 'want', 'war', 'warrior', 'watch', 'water', 'way',
       'wealthi', 'weapon', 'wed', 'week', 'weekend', 'west', 'western',
       'whi', 'white', 'widow', 'wife', 'wild', 'william', 'win', 'wish',
       'wit', 'woman', 'women', 'won', 'wonder', 'word', 'work', 'worker',
       'world', 'write', 'writer', 'written', 'wrong', 'year', 'years',
       'york', 'young', 'younger', 'youth'], dtype=object)

In [38]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similarity=cosine_similarity(vectors)
similarity

In [ ]:
def recommend(movie_name:str):
    movie_index=new_df[new_df["title"]==movie_name].index[0]
    distances=similarity[movie_index]
    movie_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [ ]:
recommend("Spectre")

In [ ]:
import pickle

In [ ]:
#pickle.dump(new_df,open("movies.pkl","wb"))

In [ ]:
pickle.dump(new_df.to_dict(),open("movie_dict.pkl","wb"))

In [ ]:
new_df.to_csv("movie_list1.csv")

In [ ]:
def prints():
    print(new_df["tags"])
print(prints())